"""Curated registry of Alberta post-secondary student services.

This is a pure data file — no scraping logic. The university_wellness.py
source plugin reads this registry and produces RawService objects.

Each institution has:
  - key: unique slug (used in tags and dedup)
  - name: official institution name
  - short_name: common abbreviation
  - city: primary campus city
  - address: main campus address
  - wellness_url: main student wellness/services hub page
  - services: list of individual services to register

Services that already exist in the DB under similar names will be
automatically skipped by the upserter's fuzzy matching (0.85 threshold).

Last verified: March 2026
"""

INSTITUTIONS = [
    # =========================================================================
    # TIER A — Large institutions (gap-fill only, most services already in DB)
    # =========================================================================
    {
        "key": "ualberta",
        "name": "University of Alberta",
        "short_name": "U of A",
        "city": "Edmonton",
        "address": "116 St & 85 Ave NW, Edmonton, AB T6G 2R3",
        "wellness_url": "https://www.ualberta.ca/en/current-students/wellness-supports/",
        "services": [
            # Already in DB: Counselling, Empower Me, First Peoples House,
            # the Landing, Psychiatry, Chaplains, Safe House, Food Bank,
            # Peer Support, Dental. Adding what's missing:
            {
                "suffix": "Accessibility Resources",
                "category": "Disability & Autism Support",
                "url": "https://www.ualberta.ca/en/current-students/accessibility-resources/",
                "phone": "(780) 492-3381",
                "description": "Provides academic accommodations, assistive technology, and support for students with disabilities at the University of Alberta.",
                "eligibility": "Current University of Alberta students with documented disabilities",
            },
            {
                "suffix": "University Health Centre",
                "category": "Healthcare Access",
                "url": "https://www.ualberta.ca/en/services/university-health-centre/",
                "phone": "(780) 492-2612",
                "description": "On-campus medical clinic providing primary healthcare, immunizations, and health assessments for University of Alberta students.",
                "eligibility": "Current University of Alberta students, staff, and faculty",
            },
        ],
    },
    {
        "key": "ucalgary",
        "name": "University of Calgary",
        "short_name": "U of C",
        "city": "Calgary",
        "address": "2500 University Dr NW, Calgary, AB T2N 1N4",
        "wellness_url": "https://www.ucalgary.ca/wellness-services",
        "services": [
            # Already in DB: Wellness Services, Harm Reduction, Recovery
            # Community, Writing Symbols Lodge, Crisis, Dental. Adding missing:
            {
                "suffix": "Student Accessibility Services",
                "category": "Disability & Autism Support",
                "url": "https://www.ucalgary.ca/pubs/calendar/current/student-accessibility-services.html",
                "phone": "(403) 220-8237",
                "description": "Academic accommodations, adaptive technology, and disability-related support for University of Calgary students.",
                "eligibility": "Current University of Calgary students with documented disabilities",
            },
            {
                "suffix": "Campus Food Bank (Students' Union)",
                "category": "Food Banks & Meals",
                "url": "https://www.su.ucalgary.ca/programs-services/student-services/food-bank/",
                "phone": "(403) 220-6551",
                "description": "Free, confidential food bank operated by the Students' Union providing grocery hampers to University of Calgary students in need.",
                "eligibility": "Current University of Calgary students",
            },
        ],
    },
    {
        "key": "mountroyal",
        "name": "Mount Royal University",
        "short_name": "MRU",
        "city": "Calgary",
        "address": "4825 Mount Royal Gate SW, Calgary, AB T3E 6K6",
        "wellness_url": "https://www.mtroyal.ca/CampusLife/StudentServices/",
        "services": [
            # Already in DB: Wellness, Iniskim Centre, Peer Support. Adding:
            {
                "suffix": "Access and Inclusion Services",
                "category": "Disability & Autism Support",
                "url": "https://www.mtroyal.ca/AcademicSupport/ResourcesServices/AccessibilityServices/index.htm",
                "phone": "(403) 440-6868",
                "description": "Supports students with disabilities through academic accommodation assessments, Canada Student Grant assistance, exam accommodations, academic strategy sessions, and assistive technology consulting.",
                "eligibility": "MRU students who fall under protected grounds as defined by Alberta Human Rights Legislation",
            },
            {
                "suffix": "SAMRU Food and Hygiene Cupboard",
                "category": "Food Banks & Meals",
                "url": "https://www.samru.ca/food-hygiene-cupboard/",
                "phone": "(403) 440-6077",
                "description": "Care Cupboard in Peer Support Centre with food and hygiene products (max 3 times/month). Satellite cupboards with refrigerated/non-perishable food restocked 4 times weekly. Free breakfasts and Good Food Box program also available.",
                "eligibility": "Current MRU students with proof of enrollment",
            },
            {
                "suffix": "Health Services",
                "category": "Healthcare Access",
                "url": "https://www.mtroyal.ca/CampusServices/WellnessServices/HealthServices/",
                "phone": "(403) 440-6326",
                "description": "Primary care medical clinic supporting students and employees. Offers medical services, mental health nurses, mental health physicians, and psychiatrists. Appointments booked by phone only.",
                "eligibility": "All credit students including occupational programs in Continuing Education",
            },
        ],
    },
    {
        "key": "macewan",
        "name": "MacEwan University",
        "short_name": "MacEwan",
        "city": "Edmonton",
        "address": "10700 104 Ave NW, Edmonton, AB T5J 4S2",
        "wellness_url": "https://www.macewan.ca/campus-life/student-services/",
        "services": [
            # Already in DB: Wellness & Psychological Services, Rainbow Clinic
            {
                "suffix": "Access and Disability Resources",
                "category": "Disability & Autism Support",
                "url": "https://www.macewan.ca/campus-life/access-and-disability-resources/",
                "phone": "(780) 497-5886",
                "description": "Creates accommodation plans removing barriers to learning for students with disabilities or medical conditions. Provides classroom/exam accommodations, assistive technology, and learning specialist support. Located in room 7-166.",
                "eligibility": "MacEwan students with documented disabilities or medical conditions",
            },
            {
                "suffix": "kihêw waciston Indigenous Centre",
                "category": "Campus & Student Services",
                "url": "https://www.macewan.ca/campus-life/kihew-waciston-indigenous-centre/",
                "phone": "(780) 497-5382",
                "description": "Indigenous student centre in Building 9 providing academic advising, mentorship, cultural programming, and access to Knowledge Keepers. Supports Indigenous students in a community environment.",
                "eligibility": "Indigenous students at MacEwan University; centre welcomes all students",
                "tags": ["indigenous"],
            },
            {
                "suffix": "SAMU Pantry — Student Food Bank",
                "category": "Food Banks & Meals",
                "url": "https://samu.ca/student-resources/health-wellness/the-pantry/",
                "phone": "(780) 633-3163",
                "description": "Confidential food hamper service available twice per month. Provides 3-5 day hampers of non-perishable food in regular, vegetarian, gluten-free, vegan, and no-pork options. Also provides hygiene items.",
                "eligibility": "All full- and part-time MacEwan students with active student ID",
            },
            {
                "suffix": "Health Centre",
                "category": "Healthcare Access",
                "url": "https://www.muhealth.ca/",
                "phone": "(780) 250-6842",
                "description": "On-campus primary care clinic operated in collaboration with U of A Department of Family Medicine. Provides medical care, health assessments, and referrals.",
                "eligibility": "Current MacEwan students and staff",
            },
        ],
    },
    {
        "key": "nait",
        "name": "NAIT",
        "short_name": "NAIT",
        "city": "Edmonton",
        "address": "11762 106 St NW, Edmonton, AB T5G 2R1",
        "wellness_url": "https://www.nait.ca/nait/student-life/health-well-being",
        "services": [
            # Already in DB: Student Counselling. Adding:
            {
                "suffix": "Learning Services — Services for Students with Disabilities",
                "category": "Disability & Autism Support",
                "url": "https://www.nait.ca/nait/student-life/academic-support",
                "phone": "(780) 378-6135",
                "description": "Advises and assists students with disabilities to achieve academic goals. Provides exam accommodations, assistive technologies, note-taking support, and the Assistive Technologies Centre.",
                "eligibility": "NAIT students with documented disabilities",
            },
            {
                "suffix": "Health Services",
                "category": "Healthcare Access",
                "url": "https://www.nait.ca/nait/student-life/on-campus/health-services/health-services",
                "phone": "(780) 471-8733",
                "description": "On-campus nursing services providing non-urgent and semi-urgent medical care, health assessments, and referrals for NAIT students.",
                "eligibility": "Current NAIT students",
            },
            {
                "suffix": "Nisohkamatotan Centre — Indigenous Student Services",
                "category": "Campus & Student Services",
                "url": "https://www.nait.ca/nait/student-life/clubs-groups-community/nisohkamatotan-centre",
                "description": "Community gathering place for Indigenous and non-Indigenous students to network, study, and access Elder support. Located in E Technical Building.",
                "eligibility": "All NAIT students; Indigenous students receive priority cultural supports",
                "tags": ["indigenous"],
            },
            {
                "suffix": "NAITSA Food Centre",
                "category": "Food Banks & Meals",
                "url": "https://naitsa.ca/service-hub/food-centre/",
                "phone": "(780) 471-8855",
                "description": "Emergency food hampers (non-perishable items) available once per month. Over 4,000 hampers distributed since 2015. Can also provide one-time referrals to Edmonton Food Bank.",
                "eligibility": "NAITSA members (credit students who pay the NAITSA fee in tuition)",
            },
        ],
    },
    {
        "key": "sait",
        "name": "SAIT",
        "short_name": "SAIT",
        "city": "Calgary",
        "address": "1301 16 Ave NW, Calgary, AB T2M 0L4",
        "wellness_url": "https://www.sait.ca/student-life/student-services",
        "services": [
            # Already in DB: Student Development & Counselling. Adding:
            {
                "suffix": "Accessibility Services",
                "category": "Disability & Autism Support",
                "url": "https://www.sait.ca/student-life/lamb-learner-success-centre/accessibility-services",
                "phone": "(403) 774-5093",
                "description": "Accommodation and accessibility supports for students with documented disabilities and medical conditions. Includes exam accommodations, assistive technology, and academic strategy support.",
                "eligibility": "SAIT students with documented disabilities (mobility, sensory, learning, attentional, neurological, psychological, or temporary)",
            },
            {
                "suffix": "Chinook Lodge Resource Centre — Indigenous Student Services",
                "category": "Campus & Student Services",
                "url": "https://www.sait.ca/indigenous-students/chinook-lodge-resource-centre",
                "phone": "(403) 210-4028",
                "description": "Gathering place for Indigenous learners to connect with peers, access advising/counselling, financial aid assistance, Elder sessions, and community events. Celebrating 20+ years of service.",
                "eligibility": "Canadian Indigenous (First Nations, Metis, Inuit) learners at SAIT",
                "tags": ["indigenous"],
            },
            {
                "suffix": "SAITSA Emergency Food Fund",
                "category": "Food Banks & Meals",
                "url": "https://saitsa.com/emergency-food-fund/",
                "description": "Emergency food funding via grocery store gift cards, pay-what-you-can fresh food markets, good food boxes, and food hampers. Available once per semester.",
                "eligibility": "Current SAIT students",
            },
            {
                "suffix": "Health Clinic",
                "category": "Healthcare Access",
                "url": "https://www.sait.ca/student-life/health-wellness-and-safety/health-clinic",
                "phone": "(403) 284-8666",
                "description": "Primary care medical clinic providing non-urgent and semi-urgent medical care to students and employees. Appointment required.",
                "eligibility": "Current active SAIT and AUArts students and employees",
            },
        ],
    },

    # =========================================================================
    # TIER B — Medium institutions (2-4 services each)
    # =========================================================================
    {
        "key": "ulethbridge",
        "name": "University of Lethbridge",
        "short_name": "U of L",
        "city": "Lethbridge",
        "address": "4401 University Dr W, Lethbridge, AB T1K 3M4",
        "wellness_url": "https://www.ulethbridge.ca/student-services",
        "services": [
            # Already in DB: Counselling Services. Adding:
            {
                "suffix": "Accessible Learning Centre",
                "category": "Disability & Autism Support",
                "url": "https://www.ulethbridge.ca/accessible-learning-centre",
                "phone": "(403) 329-2766",
                "description": "Provides individualized learning plans, exam accommodations, assistive technologies, alternate format textbooks, funding assistance, and personalized supports (educational assistants, tutors, note-takers).",
                "eligibility": "University of Lethbridge students with permanent disabilities or chronic health conditions (documentation from qualified health care practitioner required)",
            },
            {
                "suffix": "Iikaisskini Indigenous Student Centre",
                "category": "Campus & Student Services",
                "url": "https://www.ulethbridge.ca/first-nations-metis-inuit/indigenous-student-centre",
                "phone": "(403) 317-2812",
                "description": "Cultural and academic support centre located in Paterson Centre. Provides Indigenous student advising, Elder access, cultural programming, and community connection.",
                "eligibility": "Indigenous students at the University of Lethbridge; open to all students",
                "tags": ["indigenous"],
            },
            {
                "suffix": "Health Centre",
                "category": "Healthcare Access",
                "url": "https://www.ulethbridge.ca/health-centre",
                "phone": "(403) 329-2484",
                "description": "On-campus primary care clinic in the Students' Union Building providing physician clinics, nursing assessments, mental health services, and student-focused health care.",
                "eligibility": "Current University of Lethbridge students",
            },
            {
                "suffix": "ULSU Food Bank",
                "category": "Food Banks & Meals",
                "url": "https://ulsu.ca/ulsu-food-bank",
                "phone": "(403) 329-2222",
                "description": "Emergency food hampers available twice per month (max 10 visits per academic career). Also operates Little Library Food Pantries across campus.",
                "eligibility": "Current University of Lethbridge students",
            },
        ],
    },
    {
        "key": "rdpolytech",
        "name": "Red Deer Polytechnic",
        "short_name": "RDP",
        "city": "Red Deer",
        "address": "100 College Blvd, Red Deer, AB T4N 5H5",
        "wellness_url": "https://rdpolytech.ca/student-life/student-services",
        "services": [
            # Already in DB: Counselling. Adding:
            {
                "suffix": "Accessibility Services",
                "category": "Disability & Autism Support",
                "url": "https://rdpolytech.ca/student-life/student-services/accessibility-services",
                "phone": "(403) 357-3629",
                "description": "Supports students with disabilities, chronic health conditions, or temporary illnesses. Provides academic accommodations, disability-related grants, assistive technology, and the Access+ online portal.",
                "eligibility": "Red Deer Polytechnic students with documentation showing how disabilities/conditions impact academics",
            },
            {
                "suffix": "Health and Wellbeing Services",
                "category": "Healthcare Access",
                "url": "https://rdpolytech.ca/student-life/student-services/health-wellbeing-services",
                "phone": "(403) 342-3427",
                "description": "Campus nursing services providing non-urgent and semi-urgent medical care, acute care, first aid, and learner assessment. Campus physician available by appointment.",
                "eligibility": "All Red Deer Polytechnic students",
            },
            {
                "suffix": "SARDP Emergency Student Food Bank",
                "category": "Food Banks & Meals",
                "url": "https://sardp.ca/programs-services/food-bank/",
                "phone": "(403) 342-3254",
                "description": "Emergency food hampers available once per term (max twice per year). Pre-screening at Student Connect Centre required. Operates September through June.",
                "eligibility": "Currently enrolled and attending Red Deer Polytechnic students",
            },
            {
                "suffix": "Indigenous Student Services",
                "category": "Campus & Student Services",
                "url": "https://rdpolytech.ca/information/indigenous-students/indigenous-student-services",
                "phone": "(403) 342-3400",
                "description": "Academic, social, and cultural support for Indigenous students. Provides advising, funding assistance, Elder access, and cultural programming.",
                "eligibility": "First Nations, Metis, Inuit, and Non-Status students at Red Deer Polytechnic",
                "tags": ["indigenous"],
            },
        ],
    },
    {
        "key": "bowvalley",
        "name": "Bow Valley College",
        "short_name": "BVC",
        "city": "Calgary",
        "address": "345 6 Ave SE, Calgary, AB T2G 4V1",
        "wellness_url": "https://bowvalleycollege.ca/student-resources/student-life/wellness",
        "services": [
            # Already in DB: Learner Success. Adding:
            {
                "suffix": "Student Health and Wellness — Counselling Services",
                "category": "Campus & Student Services",
                "url": "https://www.bowvalleycollege.ca/student-life/student-services/student-health-wellness",
                "phone": "(403) 410-1440",
                "description": "Free counselling services including individual sessions, emergency crisis appointments, peer Wellness Mentors, and an Indigenous Counsellor providing culturally safe holistic support.",
                "eligibility": "Current Bow Valley College students",
            },
            {
                "suffix": "Accessibility Services",
                "category": "Disability & Autism Support",
                "url": "https://www.bowvalleycollege.ca/student-life/student-services/accessibility-services",
                "phone": "(403) 410-1440",
                "description": "Accessibility Advisors provide classroom and exam accommodations, assistive technology support, and learning plans for students with documented disabilities.",
                "eligibility": "Bow Valley College students with documented disabilities",
            },
            {
                "suffix": "Iniikokaan Centre — Indigenous Student Services",
                "category": "Campus & Student Services",
                "url": "https://bowvalleycollege.ca/student-resources/student-life/iniikokaan-centre",
                "phone": "(403) 476-2255",
                "description": "Programs and services supporting Indigenous student success including advocacy for Metis and First Nations funding, Elder sessions, ceremonies, and cultural programming.",
                "eligibility": "Indigenous students at Bow Valley College; centre is welcoming to all students",
                "tags": ["indigenous"],
            },
        ],
    },
    {
        "key": "norquest",
        "name": "NorQuest College",
        "short_name": "NorQuest",
        "city": "Edmonton",
        "address": "10215 108 St NW, Edmonton, AB T5J 1L6",
        "wellness_url": "https://www.norquest.ca/student-services/health-and-wellness-supports",
        "services": [
            # Already in DB: Student Wellness, Accessibility, Employment. Adding:
            {
                "suffix": "miyo-pimatisiwin Centre — Indigenous Student Services",
                "category": "Campus & Student Services",
                "url": "https://www.norquest.ca/student-services/indigenous-student-services/",
                "phone": "(780) 644-6772",
                "description": "Indigenous student centre in room 1-151 of Singhmar Centre providing Cultural Advisors, Elder access, Indigenous cultural support services, and academic/personal guidance.",
                "eligibility": "Indigenous students at NorQuest College; cultural programming open to all students",
                "tags": ["indigenous"],
            },
            {
                "suffix": "SANQC Emergency Food Bank",
                "category": "Food Banks & Meals",
                "url": "https://www.sanqc.ca/services-offered/",
                "phone": "(780) 644-6250",
                "description": "Emergency food hampers for students experiencing food insecurity. Visit the SANQC office (room 1-114, SCFL) during open hours.",
                "eligibility": "Current NorQuest College students",
            },
        ],
    },
    {
        "key": "lethbridgecollege",
        "name": "Lethbridge College",
        "short_name": "LC",
        "city": "Lethbridge",
        "address": "3000 College Dr S, Lethbridge, AB T1K 1L6",
        "wellness_url": "https://lethbridgecollege.ca/departments/wellness-services",
        "services": [
            # Already in DB: Counselling, Food Bank (via student association). Adding:
            {
                "suffix": "Accessibility Services",
                "category": "Disability & Autism Support",
                "url": "https://lethpolytech.ca/departments/accessibility-services",
                "phone": "(403) 382-6952",
                "description": "Academic accommodations, disability grant funding, technology assessment and training, academic strategies, exam accommodations, educational care attendants, and interpreters. Located in CE1341 inside the library.",
                "eligibility": "Prospective and enrolled students with documented disabilities including learning disabilities, ADHD, sensory impairments, physical disabilities, mental health disorders, and chronic medical conditions",
            },
            {
                "suffix": "Indigenous Services — Niitsitapi Gathering Place",
                "category": "Campus & Student Services",
                "url": "https://lethpolytech.ca/departments/indigenous-services",
                "phone": "(403) 320-3202",
                "description": "Circle of Services for Indigenous students including program information, admissions support, registration, study skills, Indigenous funding/awards/scholarships, and access to the Niitsitapi Gathering Place.",
                "eligibility": "First Nations, Metis, and Inuit students at Lethbridge College",
                "tags": ["indigenous"],
            },
            {
                "suffix": "Wellness Services",
                "category": "Healthcare Access",
                "url": "https://lethpolytech.ca/departments/wellness-services",
                "phone": "(403) 320-3289",
                "description": "Team of registered nurses, nurse practitioners, doctors, psychiatrists, social workers, and counsellors. Provides medical services, counselling, gender-based/sexual violence support, and referrals.",
                "eligibility": "Lethbridge College students and employees",
            },
        ],
    },
    {
        "key": "medicinehat",
        "name": "Medicine Hat College",
        "short_name": "MHC",
        "city": "Medicine Hat",
        "address": "299 College Dr SE, Medicine Hat, AB T1A 3Y6",
        "wellness_url": "https://www.mhc.ab.ca/StudentResources",
        "services": [
            # Already in DB: Mental Health and Counselling. Adding:
            {
                "suffix": "Accessibility and Tutoring Services",
                "category": "Disability & Autism Support",
                "url": "https://www.mhc.ab.ca/student-life/academic-support/accessibility",
                "phone": "(403) 529-3824",
                "description": "Exam accommodations, note-taking assistance, FM systems, CART, interpreters, and assistive technology. Students register through ClockWork Online Student Services portal.",
                "eligibility": "Medicine Hat College students with documented disabilities (documentation from specialist/professional required)",
            },
            {
                "suffix": "College Clinic — Health and Wellness",
                "category": "Healthcare Access",
                "url": "https://www.mhcollegeclinic.com/",
                "phone": "(403) 502-8437",
                "description": "On-campus medical clinic providing primary care, immunizations, and health assessments. Online appointment booking after one-time registration.",
                "eligibility": "Medicine Hat College students, employees, and community members",
            },
            {
                "suffix": "Indigenous Engagement and Student Supports",
                "category": "Campus & Student Services",
                "url": "https://www.mhc.ab.ca/campus-services/diversity-and-inclusion/indigenous-engagement",
                "phone": "(403) 504-3527",
                "description": "Indigenous engagement office providing academic, financial, and cultural support for Indigenous students.",
                "eligibility": "Indigenous students at Medicine Hat College",
                "tags": ["indigenous"],
            },
        ],
    },

    # Remaining Tier B institutions (to be populated from research):
    {
        "key": "northwestern",
        "name": "Northwestern Polytechnic",
        "short_name": "NWP",
        "city": "Grande Prairie",
        "address": "10726 106 Ave, Grande Prairie, AB T8V 4C4",
        "wellness_url": "https://www.nwpolytech.ca/mental-health-services/our-services",
        "services": [
            {
                "suffix": "Mental Health Services",
                "category": "Campus & Student Services",
                "url": "https://www.nwpolytech.ca/mental-health-services/our-services",
                "phone": "(780) 539-2911",
                "description": "Free confidential counselling by appointment. Offers one-on-one counselling, six-week Ways of Wellness group program, classroom presentations, and 24/7 Telus Health Student Support app.",
                "eligibility": "All registered Northwestern Polytechnic students",
            },
            {
                "suffix": "Accessibility Services",
                "category": "Disability & Autism Support",
                "url": "https://libguides.nwpolytech.ca/learningcommons/AccessibilityServices",
                "phone": "(780) 539-2017",
                "description": "Disability and medically-related accommodations including exam accommodations, assistive technology, and learning supports.",
                "eligibility": "Northwestern Polytechnic students with documented disabilities or medical conditions",
            },
            {
                "suffix": "On-Campus Friendship Centre",
                "category": "Campus & Student Services",
                "url": "https://www.nwpolytech.ca/student-life/indigenous-services",
                "description": "First on-campus friendship centre in Canada, a partnership between NWP and Grande Prairie Friendship Centre. Offers cultural activities, Talking Circles, and the Circle of Indigenous Students group.",
                "eligibility": "All students, with focus on Indigenous students",
                "tags": ["indigenous"],
            },
        ],
    },
    {
        "key": "lakeland",
        "name": "Lakeland College",
        "short_name": "Lakeland",
        "city": "Vermilion",
        "address": "5707 College Dr, Vermilion, AB T9X 1K5",
        "wellness_url": "https://lakelandcollege.ca/student-life-supports/",
        "services": [
            {
                "suffix": "Wellness & Counselling Services",
                "category": "Campus & Student Services",
                "url": "https://lakelandcollege.ca/student-life-supports/other-services/health-services/counsellors.html",
                "phone": "(780) 853-8516",
                "description": "Free confidential counselling at Vermilion campus covering stress, anxiety, relationships, and academic concerns. Also offers 24-hour counsellor line through student health plan at 1-877-390-7325.",
                "eligibility": "All registered Lakeland College students",
            },
            {
                "suffix": "Accessibility Services",
                "category": "Disability & Autism Support",
                "url": "https://lakelandcollege.ca/student-life-supports/academic-supports/accessibility-services.html",
                "phone": "(780) 853-8538",
                "description": "Accommodations for students with documented disabilities including exam accommodations, note takers, taping lectures, and tutors.",
                "eligibility": "Lakeland College students with documented disabilities",
            },
            {
                "suffix": "Indigenous Support Services",
                "category": "Campus & Student Services",
                "url": "https://lakelandcollege.ca/student-life-supports/indigenous-supports/index.html",
                "description": "Academic tutoring, cultural programming (beading, ribbon skirts, powwows, Talking Circles, tipi raisings), financial/emergency supports, and Elder in Residence. 30+ events per year.",
                "eligibility": "All students; Indigenous and non-Indigenous welcome",
                "tags": ["indigenous"],
            },
            {
                "suffix": "Student Food Bank",
                "category": "Food Banks & Meals",
                "url": "https://lakelandcollege.ca/student-life-supports/",
                "description": "Student food bank operated with support from the Lakeland College Students' Association.",
                "eligibility": "All Lakeland College students experiencing food insecurity",
            },
        ],
    },
    {
        "key": "olds",
        "name": "Olds College of Agriculture & Technology",
        "short_name": "Olds College",
        "city": "Olds",
        "address": "4500 50 St, Olds, AB T4H 1R6",
        "wellness_url": "https://www.oldscollege.ca/student-life/student-success/health-wellness/",
        "services": [
            {
                "suffix": "Counselling Services",
                "category": "Campus & Student Services",
                "url": "https://www.oldscollege.ca/student-life/student-success/health-wellness/counselling-services/index.html",
                "phone": "(403) 556-8238",
                "email": "counsellor@oldscollege.ca",
                "description": "Free confidential counselling available in-person at the Health & Wellness Centre and virtually. Text support available at 403-586-8255.",
                "eligibility": "All registered Olds College students",
            },
            {
                "suffix": "Accessibility Services",
                "category": "Disability & Autism Support",
                "url": "https://www.oldscollege.ca/student-life/student-success/accessibility-services/index.html",
                "email": "accessibility@oldscollege.ca",
                "description": "Accommodations for students with diagnosed disabilities, mental health diagnoses, or learning challenges. In-class and exam accommodations, tutoring, and time management workshops.",
                "eligibility": "Olds College students with documented disabilities or learning challenges",
            },
            {
                "suffix": "Indigenous Student Services",
                "category": "Campus & Student Services",
                "url": "https://oldscollege.ca/student-life/indigenous-olds-college/index.html",
                "description": "The Gathering Room in the Learning Resource Centre hosts cultural programming including monthly Soup & Bannock or Indian Taco lunches, cultural events, and student support.",
                "eligibility": "All students welcome",
                "tags": ["indigenous"],
            },
            {
                "suffix": "SAOC Pantry (Food Bank)",
                "category": "Food Banks & Meals",
                "url": "https://www.saoldscollege.ca/saoc-pantry",
                "phone": "(403) 556-4629",
                "description": "Student food pantry operated by the Students' Association of Olds College with a no-questions-asked philosophy.",
                "eligibility": "All Olds College students",
            },
        ],
    },
    {
        "key": "keyano",
        "name": "Keyano College",
        "short_name": "Keyano",
        "city": "Fort McMurray",
        "address": "8115 Franklin Ave, Fort McMurray, AB T9H 2H7",
        "wellness_url": "https://www.keyano.ca/student-services/health-and-wellness-services/",
        "services": [
            {
                "suffix": "Counselling & Wellness Services",
                "category": "Campus & Student Services",
                "url": "https://www.keyano.ca/student-services/health-and-wellness-services/",
                "phone": "(780) 791-4800",
                "email": "wellness.services@keyano.ca",
                "description": "Free confidential mental health support including one-on-one counselling and group wellness sessions. Wellness Navigator connects students to financial, housing, food, and health supports.",
                "eligibility": "All registered Keyano College students",
            },
            {
                "suffix": "Accessibility & Accommodations",
                "category": "Disability & Autism Support",
                "url": "https://www.keyano.ca/student-services/academic-support/wellness-services/",
                "phone": "(780) 791-4800",
                "description": "Academic accommodations, assistive technologies, and personalized support plans. Drop-in or appointments available.",
                "eligibility": "Keyano College students with documented disabilities",
            },
            {
                "suffix": "Bouchier Indigenous Student Centre",
                "category": "Campus & Student Services",
                "url": "https://www.keyano.ca/student-services/indigenous-students/",
                "phone": "(780) 791-4800",
                "description": "Welcoming space for cultural support, traditional learning, and connection. Offers one-on-one advising, cultural programming, and wellness support.",
                "eligibility": "All students, with focus on Indigenous students",
                "tags": ["indigenous"],
            },
        ],
    },
    {
        "key": "portage",
        "name": "Portage College",
        "short_name": "Portage",
        "city": "Lac La Biche",
        "address": "9531 94 Ave, Lac La Biche, AB T0A 2C0",
        "wellness_url": "https://portagecollege.ca/Student-Services/",
        "services": [
            {
                "suffix": "Counselling & Wellness Services",
                "category": "Campus & Student Services",
                "url": "https://portagecollege.ca/Student-Services/",
                "phone": "(780) 623-5551",
                "description": "Personal counselling, mental health support, and gender-based violence support and prevention. Mental Health Navigator and dedicated counsellors on staff. Toll-free 1-866-623-5551.",
                "eligibility": "All registered Portage College students",
            },
            {
                "suffix": "Student Learning Services (Accessibility)",
                "category": "Disability & Autism Support",
                "url": "https://portagecollege.ca/sls",
                "phone": "(780) 623-5551",
                "description": "One-on-one strategy sessions, exam accommodations, assistive technology access, and alternate format materials for students with disabilities.",
                "eligibility": "Portage College students with documented disabilities",
            },
            {
                "suffix": "Indigenous Ways of Knowing",
                "category": "Campus & Student Services",
                "url": "https://portagecollege.ca/indigenous-ways-of-knowing/student-support/",
                "phone": "(780) 623-5551",
                "description": "Indigenous student support including events, partner projects, teachings, resources, and cultural programming. Portage College also offers Native Arts and Culture programs.",
                "eligibility": "All students welcome",
                "tags": ["indigenous"],
            },
        ],
    },
    {
        "key": "northernlakes",
        "name": "Northern Lakes College",
        "short_name": "NLC",
        "city": "Slave Lake",
        "address": "1201 Main St SE, Slave Lake, AB T0G 2A3",
        "wellness_url": "https://www.northernlakescollege.ca/current-students/counselling-services",
        "services": [
            {
                "suffix": "Educational Counselling Services",
                "category": "Campus & Student Services",
                "url": "https://www.northernlakescollege.ca/current-students/counselling-services",
                "phone": "(780) 751-3222",
                "description": "Short-term non-clinical mental health and wellness supports. Toll-free 1-866-652-3456. Includes after-hours crisis resource referrals.",
                "eligibility": "All registered Northern Lakes College students",
            },
            {
                "suffix": "Accessibility Services",
                "category": "Disability & Autism Support",
                "url": "https://www.northernlakescollege.ca/current-students/accessibility-services",
                "phone": "(780) 849-8600",
                "description": "Reasonable accommodations with individualized support plans. Requires current diagnosis documentation from a qualified professional.",
                "eligibility": "Northern Lakes College students with documented disabilities",
            },
            {
                "suffix": "Virtual Indigenous Student Centre (mamawapowin)",
                "category": "Campus & Student Services",
                "url": "https://www.northernlakescollege.ca/about-us/visc",
                "phone": "(780) 849-8600",
                "description": "Virtual space bringing together resources to support Indigenous students and those learning about Indigenous culture. Serves NLC's distributed rural campus network.",
                "eligibility": "All students and community members",
                "tags": ["indigenous"],
            },
        ],
    },

    # =========================================================================
    # TIER C — Small/specialized institutions (1-3 services each)
    # =========================================================================
    {
        "key": "athabasca",
        "name": "Athabasca University",
        "short_name": "AU",
        "city": "Athabasca",
        "address": "1 University Dr, Athabasca, AB T9S 3A3",
        "wellness_url": "https://www.athabascau.ca/support-services/mental-health-and-wellness/index.html",
        "services": [
            {
                "suffix": "Mental Health & Wellness Services",
                "category": "Campus & Student Services",
                "url": "https://www.athabascau.ca/support-services/mental-health-and-wellness/index.html",
                "phone": "1-844-969-0911",
                "description": "Virtual counselling for students via Carepath by Bayshore. Certified mental health professionals provide support for stress, anxiety, depression, addiction, trauma, and relationship issues.",
                "eligibility": "Currently registered Athabasca University students (student ID required)",
                "location": "Online — Alberta-wide",
            },
            {
                "suffix": "Accessibility Services",
                "category": "Disability & Autism Support",
                "url": "https://www.athabascau.ca/support-services/accessibility-services/index.html",
                "phone": "1-800-788-9041 ext. 3424",
                "description": "Academic accommodations for students with permanent disabilities or temporary medical conditions. Uses the Accommodate online platform to process accommodation requests.",
                "eligibility": "Athabasca University students with documented disabilities or temporary medical conditions",
                "location": "Online — Alberta-wide",
            },
            {
                "suffix": "Nukskahtowin Indigenous Student Centre",
                "category": "Campus & Student Services",
                "url": "https://indigenous.athabascau.ca/",
                "phone": "1-800-788-9041 ext. 5054",
                "description": "Indigenous student support centre offering Elder advising, culturally traditional counselling, ceremonies, and a 10% tuition reduction for Indigenous undergraduates. Nukskahtowin means 'meeting place' in Cree.",
                "eligibility": "Indigenous students and all AU learners seeking Indigenous knowledge resources",
                "location": "Online — Alberta-wide",
                "tags": ["indigenous"],
            },
        ],
    },
    {
        "key": "auarts",
        "name": "Alberta University of the Arts",
        "short_name": "AUArts",
        "city": "Calgary",
        "address": "1407 14 Ave NW, Calgary, AB T2N 4R3",
        "wellness_url": "https://www.auarts.ca/our-campus/health-and-wellness",
        "services": [
            {
                "suffix": "Counselling Services",
                "category": "Campus & Student Services",
                "url": "https://www.auarts.ca/our-campus/health-and-wellness/counselling-services",
                "email": "counselling@auarts.ca",
                "description": "Free on-campus counselling offered in-person and via MS Teams. Appointments are 50 minutes; on average students attend about 3 sessions.",
                "eligibility": "Currently registered AUArts students",
            },
            {
                "suffix": "Accessibility & Accommodation Services",
                "category": "Disability & Autism Support",
                "url": "https://www.auarts.ca/our-campus/student-support/accessibility-and-accommodation-services",
                "phone": "(403) 338-5513",
                "description": "Academic accommodations for students with documented disabilities or mental health concerns. Wheelchair-accessible campus with accessible parking.",
                "eligibility": "AUArts students with documented disabilities or mental health concerns",
            },
            {
                "suffix": "Lodgepole Center — Indigenous Student Services",
                "category": "Campus & Student Services",
                "url": "https://www.auarts.ca/our-campus/the-lodgepole-center",
                "phone": "(403) 284-7600",
                "description": "Indigenous resource centre offering Elder advising, traditional ceremonies, workshops, a student gallery, and the Aahwaatkamooksi peer mentorship program.",
                "eligibility": "Indigenous, Metis, and Inuit students; open to all AUArts community members",
                "tags": ["indigenous"],
            },
        ],
    },
    {
        "key": "concordia",
        "name": "Concordia University of Edmonton",
        "short_name": "CUE",
        "city": "Edmonton",
        "address": "7128 Ada Blvd NW, Edmonton, AB T5B 4E4",
        "wellness_url": "https://concordia.ab.ca/student-services/student-life-learning/support-services/",
        "services": [
            {
                "suffix": "Short-Term Counselling Services",
                "category": "Campus & Student Services",
                "url": "https://concordia.ab.ca/student-services/student-life-learning/support-services/counselling-services/",
                "phone": "(780) 479-9241",
                "description": "Free short-term counselling for enrolled students, offered in-person at the Student Success Centre and virtually via Google Meet. Open year-round Monday to Friday.",
                "eligibility": "Currently enrolled undergraduate and graduate students at Concordia University of Edmonton",
            },
            {
                "suffix": "Student Accessibility Services",
                "category": "Disability & Autism Support",
                "url": "https://concordia.ab.ca/student-services/student-life-learning/learning-services/students-with-disabilities/",
                "email": "sas@concordia.ab.ca",
                "description": "Academic accommodations for students with documented disabilities. Advisors help develop Individual Service Plans and assist with government grant applications.",
                "eligibility": "Concordia University of Edmonton students with documented disabilities",
            },
            {
                "suffix": "CUE Cupboard Food Bank",
                "category": "Food Banks & Meals",
                "url": "https://concordia.ab.ca/student-services/student-life-learning/support-services/food-bank/",
                "email": "cuecupboard@concordia.ab.ca",
                "description": "On-campus food bank providing nutritious food and essential items. Located in Alumni Hall. Open year-round by appointment.",
                "eligibility": "Currently enrolled Concordia University of Edmonton students",
            },
            {
                "suffix": "Indigenous Knowledge & Research Centre",
                "category": "Campus & Student Services",
                "url": "https://concordia.ab.ca/student-services/indigenous-student-services/",
                "phone": "(780) 479-9394",
                "description": "A home away from home for Indigenous students offering cultural support, Elder connections, academic mentoring, and referrals to counselling, tutoring, and other campus services.",
                "eligibility": "Indigenous students at Concordia University of Edmonton; open to all community members",
                "tags": ["indigenous"],
            },
        ],
    },
    {
        "key": "kings",
        "name": "The King's University",
        "short_name": "King's",
        "city": "Edmonton",
        "address": "9125 50 St NW, Edmonton, AB T6B 2H3",
        "wellness_url": "https://www.kingsu.ca/services/student-counselling",
        "services": [
            {
                "suffix": "Student Counselling Services",
                "category": "Campus & Student Services",
                "url": "https://www.kingsu.ca/services/student-counselling",
                "phone": "(780) 465-3500",
                "description": "Free, confidential counselling with an on-campus psychologist covering stress, anxiety, depression, addictions, career counselling, and more.",
                "eligibility": "Students currently registered in classes at The King's University",
            },
            {
                "suffix": "Accessibility & Accommodations",
                "category": "Disability & Autism Support",
                "url": "https://www.kingsu.ca/services/accessibility-and-accommodation",
                "phone": "(780) 465-3500",
                "description": "Academic accommodations coordinated by the Student Support and Accessibility Coordinator for students with physical, mental health, chronic health, and neurological disabilities.",
                "eligibility": "King's University students with documented permanent or temporary disabilities",
            },
            {
                "suffix": "Indigenous Students Program",
                "category": "Campus & Student Services",
                "url": "https://www.kingsu.ca/services/indigenous-students",
                "description": "Cultural events, Indigenous heritage celebrations, Elder connections, financial aid guidance, and a dedicated on-campus room for Indigenous students.",
                "eligibility": "Indigenous students at The King's University",
                "tags": ["indigenous"],
            },
            {
                "suffix": "The Pantry — Student Food Support",
                "category": "Food Banks & Meals",
                "url": "https://www.kingsu.ca/give/other-giving-opportunities",
                "description": "Student food support program partnering with local businesses and churches. Also offers a Student Emergency Fund for food, rent, and transportation.",
                "eligibility": "King's University students in need of food assistance",
            },
        ],
    },
    {
        "key": "ambrose",
        "name": "Ambrose University",
        "short_name": "Ambrose",
        "city": "Calgary",
        "address": "150 Ambrose Circle SW, Calgary, AB T3H 0L5",
        "wellness_url": "https://ambrose.edu/wellness/counselling",
        "services": [
            {
                "suffix": "Counselling Services",
                "category": "Campus & Student Services",
                "url": "https://ambrose.edu/wellness/counselling",
                "phone": "(403) 410-2000",
                "email": "counselling@ambrose.edu",
                "description": "Free confidential individual counselling for personal, career, and academic concerns. Students receive 7 free sessions per academic year.",
                "eligibility": "Students registered for classes during the current semester at Ambrose University",
            },
            {
                "suffix": "Accessibility Services",
                "category": "Disability & Autism Support",
                "url": "https://ambrose.edu/accessibility",
                "phone": "(403) 410-2000",
                "description": "Academic accommodations for students with disabilities including alternate exam formats, assistive technology, and peer tutoring.",
                "eligibility": "Ambrose University students with documented disabilities who register each semester",
            },
        ],
    },
    {
        "key": "stmarys",
        "name": "St. Mary's University",
        "short_name": "StMU",
        "city": "Calgary",
        "address": "14500 Bannister Rd SE, Calgary, AB T2X 1Z4",
        "wellness_url": "https://stmu.ca/campus-life/student-services/",
        "services": [
            {
                "suffix": "Mental Health Counselling & Advising Services",
                "category": "Campus & Student Services",
                "url": "https://stmu.ca/campus-life/student-services/counselling-advising-services/",
                "email": "counselling@stmu.ca",
                "description": "Free, confidential mental health counselling offering 8 sessions per student per academic year. Client-centred, strength-based approach. Spiritual counselling also available via Campus Ministry.",
                "eligibility": "All currently enrolled St. Mary's University students, domestic and international",
            },
            {
                "suffix": "Accommodations & Accessibility Services",
                "category": "Disability & Autism Support",
                "url": "https://stmu.ca/campus-life/student-services/disability-resources/",
                "email": "access@stmu.ca",
                "description": "Tailored academic accommodations for students facing barriers due to medical conditions, disabilities, or non-medical protected grounds. Documentation from a licensed professional required.",
                "eligibility": "St. Mary's University students with documented disabilities or protected barriers",
            },
            {
                "suffix": "Indigenous Initiatives",
                "category": "Campus & Student Services",
                "url": "https://stmu.ca/indigenous-initiatives/",
                "description": "Academic mentoring for Indigenous learners, Elder and Knowledge-Keeper engagement, Indigenous Studies courses, and an Indigenous Advisory Council.",
                "eligibility": "Self-identified Indigenous students at St. Mary's University",
                "tags": ["indigenous"],
            },
            {
                "suffix": "Vinny's Market — Student Food Support",
                "category": "Food Banks & Meals",
                "url": "https://stmu.ca/campus-life/community/campus-ministry/",
                "email": "campus.ministry@stmu.ca",
                "description": "Free snacks and groceries for students in need, located in McGivney Hall. Run in partnership with the Society of St. Vincent de Paul.",
                "eligibility": "All St. Mary's University students",
            },
        ],
    },
    {
        "key": "burman",
        "name": "Burman University",
        "short_name": "Burman",
        "city": "Lacombe",
        "address": "6730 University Dr, Lacombe, AB T4L 2E5",
        "wellness_url": "https://www.burmanu.ca/sakalasuccesscentre/counselling",
        "services": [
            {
                "suffix": "Sakala Success Centre — Counselling Services",
                "category": "Campus & Student Services",
                "url": "https://www.burmanu.ca/sakalasuccesscentre/counselling",
                "phone": "(403) 782-3381",
                "description": "Free counselling sessions for academic, career, addiction, and personal concerns including abuse, depression, anxiety, and stress management. Appointments are individual and confidential.",
                "eligibility": "Currently enrolled Burman University students",
            },
            {
                "suffix": "Sakala Success Centre — Accessibility Services",
                "category": "Disability & Autism Support",
                "url": "https://www.burmanu.ca/sakalasuccesscentre/accessibility",
                "phone": "(403) 782-3381 ext. 4141",
                "description": "Academic and physical accommodations for students with disabilities. Disabilities Liaison assists with documentation and accessing Canada Study Grant funds.",
                "eligibility": "Burman University students with documented disabilities",
            },
        ],
    },
    {
        "key": "banffcentre",
        "name": "The Banff Centre for Arts and Creativity",
        "short_name": "Banff Centre",
        "city": "Banff",
        "address": "107 Tunnel Mountain Dr, Banff, AB T1L 1H5",
        "wellness_url": "https://www.banffcentre.ca/participant-resources",
        "services": [
            {
                "suffix": "Participant Wellness Resources",
                "category": "Campus & Student Services",
                "url": "https://www.banffcentre.ca/participant-resources",
                "phone": "(403) 762-6308",
                "email": "participant_resources@banffcentre.ca",
                "description": "Support for program participants including on-campus psychologist, walk-in counselling, mental health resources, and wellness support at Iethka Territory House of Respect.",
                "eligibility": "All Banff Centre program participants and faculty",
            },
            {
                "suffix": "Accessibility & Accommodations",
                "category": "Disability & Autism Support",
                "url": "https://www.banffcentre.ca/participant-resources/medical-information",
                "phone": "(403) 762-6123",
                "description": "Wheelchair accessible rooms, studios, dining, and meeting areas. Collaborative accommodation process for participants with disabilities.",
                "eligibility": "All Banff Centre participants requiring accommodations",
            },
            {
                "suffix": "Indigenous Participant Support",
                "category": "Campus & Student Services",
                "url": "https://www.banffcentre.ca/participant-resources/indigenous-participants",
                "description": "Culturally safe supportive listening, connections to health resources, Indigenous cultural supports, and addiction/mental health support in Treaty 7 territory.",
                "eligibility": "Indigenous program participants at the Banff Centre",
                "tags": ["indigenous"],
            },
        ],
    },
]
